### ISSUE TITLE
Unable to add as a template

### ISSUE THREAD

**Issue by authex** [zabbix/zabbix-community-repos#6]
Details:
Zabbix 2.2.9:

ERROR: Import failed
Created: Item "Windows Application Log" on "Template Windows Event Logs".
Created: Item "Windows System Log" on "Template Windows Event Logs".
Incorrect trigger expression. Check expression part starting from " and {Template Windows Event Logs:eventlog[Application,,"Warning|Error|Failure",,,,].nodata(60)}<>1".

**Comment by jangaraj** [comment]
Hi Luis,

if you have some problems with these templates/codes, *please ask author of the repo or or [Zabbix Community](http://www.zabbix.com/community.php) for help*. This repo is only list of links to Zabbix templates. We don't own this codes, so I'm closing this issue.
